# Generated by Django 4.2.5 on 2023-12-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos_app.instrutor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos_app.plano'),
        ),
    ]
